

export const technologyURLs = {
  javascript: "https://www.javascript.com/",
  typescript: "https://www.typescriptlang.org/",
  react: "https://react.dev/",
  jest: "https://jestjs.io/",
  testinglibrary: "https://testing-library.com/",
  materialui: "https://material-ui.com/",
  tailwindcss: "https://tailwindcss.com/",
  webpack: "https://webpack.js.org/",
  rollup: "https://rollupjs.org/",
  express: "https://expressjs.com/",
  mongoose: "https://mongoosejs.com/",
  mongodb: "https://www.mongodb.com/",
  python: "https://www.python.org/",
  django: "https://www.djangoproject.com/",
  aws: "https://aws.amazon.com/",
  nextjs: "https://nextjs.org/",
  vercel: "https://vercel.com/",
  docker: "https://www.docker.com/",
  jwt: "https://jwt.io/",
  jupyter: "https://jupyter.org/",
  nodejs: "https://nodejs.org/",
  npm: "https://www.npmjs.com/",
  swagger: "https://swagger.io/",
  tsnode: "https://www.npmjs.com/package/ts-node",
  pandas: "https://pandas.pydata.org/",
  
}